### ISSUE TITLE
Is there any way of wrapping the Effect library?

### ISSUE THREAD

**Issue by MelomanCool** [pyx/hymn#7]
I mean this awesome thing: https://github.com/python-effect/effect, which is basically an IO monad implementation in Python.

**Comment by pyx** [comment]
Haskell is a pure language, it's non-strict semantics makes IO Monad essential because otherwise, functions with IO and other kinds of side effects can only be written in such a language as explicit parameters (pre- IO Monad haskell, for example).

It seems the library you mentioned baked three different type of monads into one (I might be wrong as I only go through it's document moments ago): IO, Async and Retry.

One of the goat of hymn is to be able to use `>>` both in Hy and Python as a bind operator, I have no choice but implemented monads using classes, this made Monad Transformers hard to write, I've yet to figure out a way to make their implementations look good.  Unlike other monads, without Monad Transformers, IO Monad by itself in Python does not solve anything more elegantly than non-monadic IO functions, IMO.  That's why I did not implement IO Monad, even though it will be within a screenful of code.

Async monad is something I've always wanted in hymn, I was waiting for async support in Hy (`defn/a` et al.) to make it happened. I did add a synchronous one called `Lazy` though.

In situations that I need Retry (for IO), I usually wrap IO functions inside error handling monads (Maybe, Either) by using `maybe` e.g `(setv input-m (maybe input))` or `failsafe` and work from there.

Do you have a concrete use case of IO monad in python?

**Comment by MelomanCool** [comment]
> Haskell is a pure language, it's non-strict semantics makes IO Monad essential
No, that's not my goal. I want not purity, but practicality.

> Do you have a concrete use case of IO monad in python?
I would like to test IO code, that's all. Pure functions are not always enough, especially when you are interacting with a user.

**Comment by MelomanCool** [comment]
The Effect allows you to use generators to communicate with outside world.
```python
def get_user_name():
    return Effect(ReadLine("Enter User Name> "))

@do
def greet():
    try:
        name = yield get_user_name()
    except Exception as e:
        yield Effect(Print("There was an error!", e))
    else:
        yield Effect(Print("Hello,", name))
```
And then you can test the code:
```python
@do
def code_under_test():
    r = yield Effect(MyIntent('a'))
    r2 = yield Effect(OtherIntent('b'))
    yield do_return((r, r2))

def test_code():
    seq = [
        (MyIntent('a'), lambda i: 'result1'),
        (OtherIntent('b'), lambda i: 'result2')
    ]
    eff = code_under_test()
    assert perform_sequence(seq, eff) == ('result1', 'result2')
```
And while that's pretty convenient, I am not very happy with trading generators for that.


> One of the goat of hymn is to be able to use >> both in Hy and Python as a bind operator
Well, it's better to have a half of something than to have nothing at all.

**Comment by pyx** [comment]
> No, that's not my goal. I want not purity, but practicality.

I meant, IO as Monad is good for Haskell, not necessarily the case for Python.

The Hindley–Milner type system is so powerful, that it will prevent any side effect that's not explicitly declared from happening. It's (almost) impossible to do IO inside a function if it's type signature is not `IO a`.

Without the protection of HM type system, I think it's more practical to use IO functions directly in Python. When I do IO, I will isolate IO routines from business logic as best as I can, no matter in what language I am writing.

For example, this is what I will write:
```python
def get_user_name():
    return input("Enter User Name> ")

def greet():
    try:
        name = get_user_name()
    except Exception as e:
        print("There was an error!", e)
    else:
        print("Hello,", name)
```

To make code easier to test, **separation of concerns is the key**, not by using monads. Monads help us to compose things (by well defined interfaces, `bind`, `fmap`, `join`, `unit`, 3 monad laws, etc.), not to separate concerns.

So, this is how I do it, notice `code_under_test`, `do_something_1` and `do_something_2` are all pure functions:
```python
def code_under_test(a, b):
    r1 = do_something_1(a)
    r2 = do_something_2(b)
    return (r1, r2)

def test_code():
    seq = ['result1', 'result2']
    assert code_under_test('a', 'b') == ('result1', 'result2')
```

IMO, functions implementing business logic should be pure functions, we can then test the business logic without worrying about user input, and we should test routines that handle user input separately.

To handle user input (that might fail), in a monadic way, this is what I will do (using Either monad and helper decorator `failsafe` I mentioned above):

```clojure
(require [hymn.macros [do-monad-return]])
(import [hymn.dsl [failsafe Right]])

(setv input-m (failsafe input))

(setv
  a (input-m "enter a: ")
  b (input-m "enter b (same as a to pass test): "))

(print "test: " a "=" b)
(assert (= a b))
(print "test passed")

(defn process-m [ma mb]
  (do-monad-return
    [a ma
     b mb]
     [a b]))

(setv
  a (input-m "enter a (\"asdf\" to pass test): ")
  b (input-m "enter b (\"1234\" to pass test): "))

(print "test: process-m(" a ", " b ")")
(assert (= (process-m a b) (Right ["asdf" "1234"])))
(print "test passed")

(assert (= (process-m (Right "hello") (Right "world")) (Right ["hello" "world"])))
```

In either (pun not intended) case, I do not understand the need of a specifically designed IO monad. Please correct me if I am wrong.

**Comment by MelomanCool** [comment]
Hello, and sorry for my late response. Thank you for your explanation.
